try {
  a = 1;
}
catch (w) { }

console.log(a);
